// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaw7EKwmJp5br515BasJmTcu2f89kr-b8',
    appId: '1:208497786566:web:a32dfd5387095b2507a1c7',
    messagingSenderId: '208497786566',
    projectId: 'mymeal-app-a205c',
    authDomain: 'mymeal-app-a205c.firebaseapp.com',
    storageBucket: 'mymeal-app-a205c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8KYOEAMoYXNjVcFaO9T3_jbKqFT2LgQg',
    appId: '1:208497786566:android:7f6933ec8546334207a1c7',
    messagingSenderId: '208497786566',
    projectId: 'mymeal-app-a205c',
    storageBucket: 'mymeal-app-a205c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-P4avyBwKsbOALavcTFGZzo7ge57JVpU',
    appId: '1:208497786566:ios:e26ba242bad6c61f07a1c7',
    messagingSenderId: '208497786566',
    projectId: 'mymeal-app-a205c',
    storageBucket: 'mymeal-app-a205c.firebasestorage.app',
    iosBundleId: 'com.example.mymealApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-P4avyBwKsbOALavcTFGZzo7ge57JVpU',
    appId: '1:208497786566:ios:e26ba242bad6c61f07a1c7',
    messagingSenderId: '208497786566',
    projectId: 'mymeal-app-a205c',
    storageBucket: 'mymeal-app-a205c.firebasestorage.app',
    iosBundleId: 'com.example.mymealApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaw7EKwmJp5br515BasJmTcu2f89kr-b8',
    appId: '1:208497786566:web:6c74b0a28aa864f207a1c7',
    messagingSenderId: '208497786566',
    projectId: 'mymeal-app-a205c',
    authDomain: 'mymeal-app-a205c.firebaseapp.com',
    storageBucket: 'mymeal-app-a205c.firebasestorage.app',
  );
}
